# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 14:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180102_1305'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('states', django.db.models.manager.Manager()),
            ],
        ),
    ]
