# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_img',
            field=models.ImageField(default='/covers/default_cover.jpeg', null=True, upload_to=movies.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=140),
        ),
    ]
